### ISSUE TITLE
1.0 API Connection Issue

### ISSUE THREAD

**Issue by wolveix** [wolveix/satisfactory-server#260]
## **STATUS**
IT WORKS 🎉

You shouldn't have any issues with the latest docker image (image hash `b02914a46b1d`). Available via the tags below:
- `latest`
- `dev`
- `1.7.3`
- `1.7`

## **OLD WORKAROUND**
You can get around the game's bug by opening your container completely, or by explicitly providing it with an IPv6 configuration (you can still connect via IPv4):

For Docker run:
Add `--net=host` before `wolveix/satisfactory-server:latest`

For Docker Compose:
Add `network_mode: host` below `image`:
```yaml
image: 'wolveix/satisfactory-server:latest'
network_mode: host
```

To use IPv6 (for Docker Compose):
```
    image: 'wolveix/satisfactory-server:latest'
    networks:
      - satisfactory

networks:
  satisfactory:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
```

## **Summary**

I spoke with a Coffee Stain developer for a while and we troubleshooted together to figure out the issue. Essentially, there's an issue with how the TCP bind for the API disregards multihoming. You can reproduce the issue we see with the container by running it on baremetal with `-multihome` set to anything. No, we are not using `-multihome` within the container. Yes, this is an issue we need to wait for them to fix.

They've confirmed that the patch will be released tomorrow (September 11th)!

**Comment by chichi13** [comment]
Good Luck!

**Comment by wolveix** [comment]
No, it's not because of that.

The API binds to a random port right now, looking for a config flag for it

**Comment by wolveix** [comment]
You can get around the issue for now by running `net=host` for the container

https://docs.docker.com/engine/network/drivers/host/

**Comment by wolveix** [comment]
I'll continue searching for the flag, assuming CoffeeStain added one that is

**Comment by iceyy0044** [comment]
Can i somehow do that when iam using the docker image inside pterodactyl egg ? Or i need to wait for the author to fix it aswell ?

**Comment by Tctcl** [comment]
> Can i somehow do that when iam using the docker image inside pterodactyl egg ? Or i need to wait for the author to fix it aswell ?

I'll fork the official egg and send a link in here for that

**Comment by iceyy0044** [comment]
Okay, thanks.

**Comment by ankemp** [comment]
> You can get around the issue for now by running `net=host` for the container
> 
> https://docs.docker.com/engine/network/drivers/host/

Can't do this when you bind to a static IP on a different subnet, ideally we can configure the port manually.

**Comment by dbaje** [comment]
The network host workaround is not a one size fits all solution. If you are forwarding requests from one server to another, that's also an issue.

**Comment by dbaje** [comment]
> by any chance, i deployed it on a truenas scale instance custom app, how do i change the network mode, if somehow someone know that

You can't. One way to do it in scale, is to bind your container to the network bridge so it can get an IP address and then you connect to that IP.

**Comment by DenuxPlays** [comment]
The image only downloaded 60MB is this right?
So the server from steam is 60MB?

**Comment by EuleMitKeule** [comment]
How can I fix it when using Docker Swarm? I don't think `network_mode: host` is an option there.

**Comment by stirkage** [comment]
> The image only downloaded 60MB is this right? So the server from steam is 60MB?

It will download the game server files on first launch

**Comment by DenuxPlays** [comment]
> > The image only downloaded 60MB is this right? So the server from steam is 60MB?
> 
> 
> 
> It will download the game server files on first launch

The container is running
The container logs reported that he downloaded 60MB

**Comment by ankemp** [comment]
@wolveix 

From the official docs (found in game install dir):

Dedicated Server API consists of two separate endpoints, both operating on the same port as the game server, which is normally 7777. 
If the server port is changed (through Engine.ini configuration file, or through -Port= command line argument), the API will listen on the
specified port instead.

**Comment by Fabricio20** [comment]
For future reference, these seem to be all available command options under unix, includes one for the http api `-httpproxy=ADDRESS:PORT`.

![image](https://github.com/user-attachments/assets/134b85de-9ceb-4889-aa1c-8471378b65c7)

**Comment by iceyy0044** [comment]
> @wolveix
> 
> From the official docs (found in game install dir):
> 
> Dedicated Server API consists of two separate endpoints, both operating on the same port as the game server, which is normally 7777. If the server port is changed (through Engine.ini configuration file, or through -Port= command line argument), the API will listen on the specified port instead.

Does not help me sadly.. running my server on port 2010 and still getting "Failed to Connect to the Server API" when joining using port 2010. Idk if i understood it right tho..

**Comment by wolveix** [comment]
> @wolveix
> 
> From the official docs (found in game install dir):
> 
> Dedicated Server API consists of two separate endpoints, both operating on the same port as the game server, which is normally 7777. If the server port is changed (through Engine.ini configuration file, or through -Port= command line argument), the API will listen on the specified port instead.

Where are you seeing these docs?

**Comment by EuleMitKeule** [comment]
@wolveix `steamapps\common\Satisfactory\CommunityResources\DedicatedServerAPIDocs.md`

**Comment by ankemp** [comment]
@wolveix 

`PATH\TO\YOUR\INSTALL\CommunityResources\DedicatedServerAPIDocs.md`

**Comment by wolveix** [comment]
Thanks guys!

**Comment by wolveix** [comment]
Those docs don't seem to be right. It's completely disregarding the flags

**Comment by ImKringle** [comment]
My own with that set *seems* to accept it, but it doesnt do anything with it.. Weird.
```
[2024.09.10-15.57.34:891][  0]LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled
[2024.09.10-15.57.34:892][  1]LogHttp: Warning: 0x7fdaa4819760: request failed, libcurl error: 7 (Couldn't connect to server)
[2024.09.10-15.57.34:892][  1]LogHttp: Warning: 0x7fdaa4819760: libcurl info message cache 0 (  Trying 50.20.249.105:2305...)
[2024.09.10-15.57.34:892][  1]LogHttp: Warning: 0x7fdaa4819760: libcurl info message cache 1 (connect to 50.20.249.105 port 2305 failed: Connection refused)
[2024.09.10-15.57.34:892][  1]LogHttp: Warning: 0x7fdaa4819760: libcurl info message cache 2 (Failed to connect to 50.20.249.105 port 2305 after 4 ms: Couldn't connect to server)
[2024.09.10-15.57.34:892][  1]LogHttp: Warning: 0x7fdaa4819760: libcurl info message cache 3 (Closing connection)
```

**Comment by wolveix** [comment]
As far as I can tell, there's just no way to specify the API port right now. The bind works for the game port, but not the API port

**Comment by iceyy0044** [comment]
> As far as I can tell, there's just no way to specify the API port right now. The bind works for the game port, but not the API port

Well i opened the port 7777, assigned it to my server but still does not work .. also tryed having the main port the same as the api port and also did not help .. still getting same api error when connecting..

**Comment by EuleMitKeule** [comment]
So can we just change the game port and let the API port take 7777? I am not really understanding what the problem is, is there a port conflict?

**Comment by wolveix** [comment]
The issue is that we can't configure the API port. That's it

**Comment by iceyy0044** [comment]
Well shouldn't it work with the default one then ? (it does not)

**Comment by wolveix** [comment]
There isn't a default port for it, it appears to dynamically bind at runtime

**Comment by wolveix** [comment]
Yep, confirmed, it randomly binds on startup. Nothing I can do about it either until Coffee Stain fixes the issue, we find a secret flag to specify it, or...

**Comment by wolveix** [comment]
Oh you know what it is?

**Comment by iceyy0044** [comment]
Oh well thats ass .. so like on each restart it changes right ? Probably on an private machine opening all ports could work then .. but on commercial host machine it is not a possibility to prevent anyone getting in the machine ..

**Comment by ImKringle** [comment]
Not finding anything in the config, docs, or anything online with any helpful information here. we quite literally just need coffeestain to release a fix

**Comment by noahjahn** [comment]
Hmm, my server logs show that the http server is running on port 7777, but it's bound to localhost rather than `0.0.0.0`. This would explain why setting network mode to host resolves the issue.

```
[2024.09.10-15.52.37:273][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7777
[2024.09.10-15.52.37:273][  0]LogServer: Display: Server API listening on '0.0.0.0:7777' (Standalone)
```

**Comment by 1n5aN1aC** [comment]
In theory, we could have a script running inside the container, which would run netstat or similar, and once it sees the port listening, it could start up an internal proxy to connect X (configured) external port to the discovered internal port.

But that sounds like a lot of work and mess...

**Comment by wolveix** [comment]
Lol, yeah sorry guys, my message a few messages back still applies. 

In the log, it'll say that the API can't bind to 7777 as it's already in-use. So I figured, huh, I'll change the port to 7778 then. That "fixed" the issue in the log, but it doesn't actually change anything lol. So the game then binds to that port (instead of 7777), but the API still binds to a dynamic port.

So unless we find a secret config option (I don't think there is one, I think this is an unfortunate blunder on Coffee Stains' part), we can't do anything until they fix it. 

In the meantime, you can get around this by running your container with network mode set to `host` (details above)

**Comment by xyzjesper** [comment]
> I think I've figured out a fix, one sec

There a fix?

**Comment by EuleMitKeule** [comment]
network_mode does not work with Docker Swarm 😭

**Comment by kivle** [comment]
https://steamcommunity.com/app/526870/discussions/1/4751949102181378614/?ctp=2 

Interesting discussion in the Steam forums. It seems removing "-multihome=0.0.0.0" from a service file has fixed it for some. You then also get a certificate confirmation request first time you connect to the server since the server uses a random self-signed certificate for the HTTPS API.

**Comment by ikiris** [comment]
we should not have multihome in the code anymore. it overridees things that shouldn't be now.

**Comment by wolveix** [comment]
Multihome isn't in-use here, and I've tested with it explicitly removed too

**Comment by ikiris** [comment]
https://questions.satisfactorygame.com/post/66e068e6772a987f4a8a98c9

**Comment by shredoo** [comment]
> Lol, yeah sorry guys, my message a few messages back still applies.
> 
> In the log, it'll say that the API can't bind to 7777 as it's already in-use. So I figured, huh, I'll change the port to 7778 then. That "fixed" the issue in the log, but it doesn't actually change anything lol. So the game then binds to that port (instead of 7777), but the API still binds to a dynamic port.
> 
> So unless we find a secret config option (I don't think there is one, I think this is an unfortunate blunder on Coffee Stains' part), we can't do anything until they fix it.
> 
> In the meantime, you can get around this by running your container with network mode set to `host` (details above)

so does this random API port stay until reboot or is this a per-connection thing?

I assume I'll need to open this on my firewall for people to connect outside of my network

**Comment by ikiris** [comment]
https://github.com/wolveix/satisfactory-server/blob/0920005263b854bc90323864c0d74fc9d984da8a/run.sh#L123

remove the multihome bit

**Comment by wolveix** [comment]
@ikiris it isn't called by default, and I've already removed it

**Comment by iceyy0044** [comment]
In the satisfactory pterodactyl egg there was still the multihome thing on startup and it seems like it helped when i removed it as now i can connect to the server, load my save and play..

**Comment by iceyy0044** [comment]
I did get an notification that the server does not have a certificate or something like that when connecting first time but if it works iam okay to live with that untill a true fix is out..

**Comment by cheGGo** [comment]
quickfix until @wolveix has fixed it:

jump into your running docker container:

`docker exec -it <containername> /bin/bash`

Im Container:
```
apt update
apt install vim
vim /home/steam/
vim /home/steam/run.sh
```

edit last line to: 
`exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "$@"`

`exit `
(from docker container)

`docker restart <container-name>`

have fun.

**Comment by wolveix** [comment]
@cheGGo that does not work for me

**Comment by lennartdohmann** [comment]
@cheGGo this does not work for me as well

**Comment by krazysh01** [comment]
@cheGGo No luck from here either, still getting the same Failed to connect to the Server API error. did you change any other config?

**Comment by cradickDEV** [comment]
@cheGGo worked for me. changed the run.sh and the docker network-mode to host

**Comment by 1n5aN1aC** [comment]
> quickfix until @wolveix has fixed it:

Didn't work for me.

**Comment by wolveix** [comment]
@cradickDEV no, changing the network mode fixed it for you

**Comment by MadsHT** [comment]
I got it working by setting this `network_mode: 'host'` in the docker-compose and then setting the server IP using the `environment` list

**Comment by xyzjesper** [comment]
Is it fixed?

**Comment by cheGGo** [comment]
@wolveix  uhm... you're right - with that i was able to setup the dedidacted server in game with an admin pass, but starting a new game on that server isnt working .. sorry for confusion :(

**Comment by MadsHT** [comment]
> > I got it working by setting this `network_mode: 'host'` in the docker-compose and then setting the server IP using the `environment` list
> 
> The network mode host is just a bandaid, not a proper fix. For example that won't work on docker swarm.

Agreed.. But until coffe stain games with a fix, i guess this will do.. 🤔

**Comment by xyzjesper** [comment]
> @cradickDEV no, changing the network mode fixed it for you

have you fix it?

**Comment by natewalck** [comment]
> @cheGGo worked for me. changed the run.sh and the docker network-mode to host

Try rebooting your server. Does it retain the config changes?

**Comment by xyzjesper** [comment]
Ahh yes i mean it is working

**Comment by Thieseract** [comment]
> I got it working by setting this `network_mode: 'host'` in the docker-compose and then setting the server IP using the `environment` list

Could you share what your .yml file looks like? I have tried this but I am still getting the Server API error message and I am not sure what I could be doing incorrectly.

**Comment by wolveix** [comment]
I'm speaking with one of the Coffee Stain devs now. It seems it's the IPv6 binding that's going to a random port. Examples:

```
root@petaluma:/home/rthomas# lsof -i -P -n | grep LISTEN
FactorySe 3563885  rthomas   13u  IPv4 50850947      0t0  TCP *:7778 (LISTEN)
FactorySe 3563885  rthomas   14u  IPv6 50850948      0t0  TCP *:51771 (LISTEN)
```

```
root@petaluma:/home/rthomas# lsof -i -P -n | grep LISTEN
FactorySe 3553731  rthomas   13u  IPv4 50811103      0t0  TCP *:7777 (LISTEN)
FactorySe 3553731  rthomas   14u  IPv6 50811104      0t0  TCP *:40497 (LISTEN)
```

**Comment by EuleMitKeule** [comment]
Any ideas on how a temporary fix could look like when network_mode: host is not an option? When I know what random port was chosen, could I for example use a reverse proxy to expose this port? How do I tell the game how to find the API then?

**Comment by MadsHT** [comment]
@Thieseract 
> Could you share what your .yml file looks like? I have tried this but I am still getting the Server API error message and I am not sure what I could be doing incorrectly.

``` yaml
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
          - '/home/surftown/docker/game_servers/satisfactory-server/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
            - DISABLESEASONALEVENTS=true
            - SERVERIP=192.168.1.135
        restart: unless-stopped
        network_mode: 'host'
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 12G
```

This is my current compose file

**Comment by noahjahn** [comment]
@wolveix, they need to bind the HTTP listener to 0.0.0.0, not `127.0.0.1`. The HTTP API is accessibly within the container, but not outside.

**Comment by ImKringle** [comment]
> @wolveix, they need to bind the HTTP listener to `0.0.0.0`, not `127.0.0.1`. The HTTP API is accessibly within the container, but not outside.

This ^

**Comment by wolveix** [comment]
Relayed, thank you!

**Comment by ikiris** [comment]
well, if its ipv6 ::

**Comment by LucasGenoud** [comment]
> I'm speaking with one of the Coffee Stain devs now
That's some top level support right here ! Thank you for your work !

**Comment by Sephzer** [comment]
```
[2024.09.10-16.37.38:302][  0]LogServer: Warning: Failed to bind Socket 'FGServerAPISocket' To Address '127.0.0.1:7777': SE_EADDRINUSE
[2024.09.10-16.37.38:302][  0]LogHttpListener: Warning: HttpListener unable to set desired buffer size (524288): Limited to 425984
[2024.09.10-16.37.38:302][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7777
[2024.09.10-16.37.38:303][  0]LogServer: Display: Server API listening on '0.0.0.0:7777' (Standalone)
[2024.09.10-16.37.38:303][  0]LogServer: Display: Server API listening on '[::]:7777' (Standalone)
```

Anything to do with 'FGServerAPISocket'. This is currently in host mode, wondering if this is a variable we can set somewhere.

**Comment by gotanks0407** [comment]
> I'm speaking with one of the Coffee Stain devs now. It seems it's the IPv6 binding that's going to a random port. 

I thought =multihome was suppose to disable IPv6 on linux dedicated servers. I guess this must have changed for 1.0

**Comment by TOoSmOotH** [comment]
Thanks for digging into this everyone!

**Comment by wolveix** [comment]
Updates. The binding to `127.0.0.1` thing is just a logging thing, they said to ignore it. `-multihome` fixes the second port being dynamic, but doesn't replace it with anything, resulting in the same "unable to reach API" error

**Comment by cheGGo** [comment]
well, removing the OPTIONS mentioned in my deleted command so that run.sh only contains:

container file: /home/steams/run.sh: 
`exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "$@"`

restarting container without pull or remove that container is starting a functional server for me.

it seems to be related that I'm running in docker network mode 'host' (and ipv6 enabled!) 
 
After that I can connect to the server in game and set up an admin password and create a new game 
(which seemed at first to be not working, but its creating a new save and I can join it)

**Comment by 98jan** [comment]
Deployment on Kubernetes working for me with image tag "dev", I needed to add following environment variables:

```
        - name: AUTOPAUSE
          value: "true"
        - name: AUTOSAVEINTERVAL
          value: "300"
        - name: AUTOSAVENUM
          value: "10"
        - name: AUTOSAVEONDISCONNECT
          value: "true"
        - name: SKIPUPDATE
          value: "false"
        - name: MAXPLAYERS
          value: "4"
        - name: TZ
          value: Europe/Berlin
        - name: CRASHREPORT
          value: "false"
        - name: ROOTLESS
          value: "false"
        - name: STEAMBETA
          value: "false"
```

Running in rootless mode is failing right now for me.

**Comment by wolveix** [comment]
@cheGGo yes, again, it's because you're using network=host

**Comment by cheGGo** [comment]
> @cheGGo yes, again, it's because you're using network=host

nope, was running network mode host before and it wasnt working until I removed multihome from `run.sh`

**Comment by 98jan** [comment]
nope, no network=host is used, service is exposed as LoadBalancer and only on 7777:

![image](https://github.com/user-attachments/assets/ce861b21-cefb-4eb9-9556-a6c9a31b25c5)

**Comment by cradickDEV** [comment]
> > @cheGGo yes, again, it's because you're using network=host
> 
> nope, was running network mode host before and it wasnt working until I removed multihome from `run.sh`

same for me. only networkmode host and the run command together is working

**Comment by chnagy** [comment]
setting host mode only didn't work for me. In combination with the command of @cheGGo it worked

**Comment by noahjahn** [comment]
> Updates. The binding to `127.0.0.1` thing is just a logging thing, they said to ignore it. `-multihome` fixes the second port being dynamic, but doesn't replace it with anything, resulting in the same "unable to reach API" error

I can `curl` the API when I'm shelled into the container, but cannot through the port binding on the host computer where docker is running. Though, to their point I do see just an SSL error. Maybe we need to need to do some sort of volume mapping for the generated SSL certificate?

Inside the container:

```
root@7651dedef588:/config# curl -k https://localhost:7777
{"errorCode": "errors.com.epicgames.httpserver.route_handler_not_found", "errorMessage": ""}
```

outside the container:

```
curl -k https://localhost:7777
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:7777
```

**Comment by natewalck** [comment]
> well, removing the OPTIONS mentioned in my deleted comment so that run.sh only contains:
> 
> container file: /home/steams/run.sh: `exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "$@"`
> 
> restarting container without pull or remove that container is starting a functional server for me.
> 
> it seems to be related that I'm running in docker network mode 'host' (and ipv6 enabled!)
> 
> After that I can connect to the server in game and set up an admin password and create a new game (which seems at first not to be working, but its creating a new save and I can join it)
> 
> proof: ![image](https://private-user-images.githubusercontent.com/8850080/366135537-c7ea57a0-a7a7-42c6-bbab-91ec1444a752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODc2MDIsIm5iZiI6MTcyNTk4NzMwMiwicGF0aCI6Ii84ODUwMDgwLzM2NjEzNTUzNy1jN2VhNTdhMC1hN2E3LTQyYzYtYmJhYi05MWVjMTQ0NGE3NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTY1NTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU3ZTQ4MTliYmU2MzVjNDA5OGRhYTgyYTE4ZjM2N2JmZWNmN2MwMDk4MGZmYzBkMjg5ZGI2M2ZmZWM4MmQ2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pwvb-df7_5trwU4NVp0N3VeAy4u0m-uiYpuBVwDabU4)

Restart the container and see if it is still there when it comes back up. I think there is a secondary issue outside of the 1.0 API connection. (See #266)

**Comment by Cisor** [comment]
> exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "$@"

This is working for me in combination with network_mode: 'host'

Without the run.sh hack, I could not connect

This only affected the server when running in Docker on a separate host. 
Docker locally worked without the run.sh change


Many thanks to @cheGGo for the workaround and to @wolveix for creating this container in the first place

**Comment by dieser-niko** [comment]
@cheGGo  
> it seems to be related that I'm running in docker network mode 'host' (and ipv6 enabled!)

Is IPv6 actually important? I don't have it enabled in my docker configuration and it doesn't seem to work (but it's my first time setting up satisfactory)

**Comment by AsterAether** [comment]
Can confirm @noahjahn report, HTTPS connections only seem to work inside the container.

**Comment by Igeling** [comment]
> > @cheGGo yes, again, it's because you're using network=host
> 
> nope, was running network mode host before and it wasnt working until I removed multihome from `run.sh`
I can confirm that as well

**Comment by myrcutio** [comment]
is there any guidance on a k8s pod spec? I tried adding `hostNetwork: true`  but now my pod is stuck in a pending state

**Comment by cheGGo** [comment]
> @cheGGo
> 
> > it seems to be related that I'm running in docker network mode 'host' (and ipv6 enabled!)
> 
> Is IPv6 actually important? I don't have it enabled in my docker configuration and it doesn't seem to work (but it's my first time setting up satisfactory)

i dont think so, i mentioned it because it was a troubleshooting path before, so I just want to be sure no one thinks I've disabled ipv6 to get it working

**Comment by Sephzer** [comment]
> > well, removing the OPTIONS mentioned in my deleted comment so that run.sh only contains:
> > container file: /home/steams/run.sh: `exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "$@"`
> > restarting container without pull or remove that container is starting a functional server for me.
> > it seems to be related that I'm running in docker network mode 'host' (and ipv6 enabled!)
> > After that I can connect to the server in game and set up an admin password and create a new game (which seems at first not to be working, but its creating a new save and I can join it)
> > proof: ![image](https://private-user-images.githubusercontent.com/8850080/366135537-c7ea57a0-a7a7-42c6-bbab-91ec1444a752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODc2MDIsIm5iZiI6MTcyNTk4NzMwMiwicGF0aCI6Ii84ODUwMDgwLzM2NjEzNTUzNy1jN2VhNTdhMC1hN2E3LTQyYzYtYmJhYi05MWVjMTQ0NGE3NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTY1NTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU3ZTQ4MTliYmU2MzVjNDA5OGRhYTgyYTE4ZjM2N2JmZWNmN2MwMDk4MGZmYzBkMjg5ZGI2M2ZmZWM4MmQ2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pwvb-df7_5trwU4NVp0N3VeAy4u0m-uiYpuBVwDabU4)
> 
> Restart the container and see if it is still there when it comes back up. I think there is a secondary issue outside of the 1.0 API connection. (See #266)

FYI I just tried this, restarted my container and my server settings/game that I created persisted.

**Comment by ikiris** [comment]
can yall stop spamming the bug? its already at 100 comments and most of them unproductive

**Comment by Obscured84** [comment]
dump question, sorry if already tried.

port 7777 should be default, what happens if you get rid of the -port parameter?

**Comment by cheGGo** [comment]
> > well, removing the OPTIONS mentioned in my deleted comment so that run.sh only contains:
> > container file: /home/steams/run.sh: `exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "$@"`
> > restarting container without pull or remove that container is starting a functional server for me.
> > it seems to be related that I'm running in docker network mode 'host' (and ipv6 enabled!)
> > After that I can connect to the server in game and set up an admin password and create a new game (which seems at first not to be working, but its creating a new save and I can join it)
> > proof: [...]
> 
> Restart the container and see if it is still there when it comes back up. I think there is a secondary issue outside of the 1.0 API connection. (See #266)

restarting container works perfectly well - done create a new instance or pull a new version of the container after change the `run.sh`command.

**Comment by iddqd0** [comment]
so is it impossible to host right now without using host mode for Docker networking?

**Comment by EuleMitKeule** [comment]
I deployed a container with network_mode host and modified the exec command in run.sh and changed the port but I still can not connect.

```4.09.10-17.05.51:133][  0]LogServer: Warning: Server API is running using a Self-Signed Certificate.
[2024.09.10-17.05.51:133][  0]LogServer: Warning: To verify the certificate integrity on the Client, make sure the following Fingerprint matches with the Client one:
[2024.09.10-17.05.51:133][  0]LogServer: Warning: SHA256:u1KDc80gSsVc1lLbxf/vBwS3UMWIyC//m3wJtT68M3E=
[2024.09.10-17.05.51:133][  0]LogServer: Warning: ==============================================================
[2024.09.10-17.05.51:133][  0]LogServer: Warning: Failed to bind Socket 'FGServerAPISocket' To Address '127.0.0.1:7817': SE_EADDRINUSE
[2024.09.10-17.05.51:133][  0]LogHttpListener: Warning: HttpListener unable to set desired buffer size (524288): Limited to 425984
[2024.09.10-17.05.51:133][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7817
[2024.09.10-17.05.51:134][  0]LogServer: Display: Server API listening on '0.0.0.0:7817' (Standalone)
[2024.09.10-17.05.51:134][  0]LogServer: Display: Server API listening on '[::]:7817' (Standalone)```

**Comment by cheGGo** [comment]
> I deployed a container with network_mode host and modified the exec command in run.sh and changed the port but I still can not connect.
> 
> ```
> 
> [2024.09.10-17.05.51:133][  0]LogServer: Warning: ==============================================================
> [2024.09.10-17.05.51:133][  0]LogServer: Warning: Failed to bind Socket 'FGServerAPISocket' To Address '127.0.0.1:7817': SE_EADDRINUSE
> [2024.09.10-17.05.51:133][  0]LogHttpListener: Warning: HttpListener unable to set desired buffer size (524288): Limited to 425984
> [2024.09.10-17.05.51:133][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7817
> [2024.09.10-17.05.51:134][  0]LogServer: Display: Server API listening on '0.0.0.0:7817' (Standalone)
> [2024.09.10-17.05.51:134][  0]LogServer: Display: Server API listening on '[::]:7817' (Standalone)```
> ```

u should see a connection attempt… even it’s not working. so I think you got another problem

**Comment by EuleMitKeule** [comment]
@cheGGo I do, but the server shows as "offline" in the menu.
```
[2024.09.10-17.05.51:133][  0]LogServer: Warning: Failed to bind Socket 'FGServerAPISocket' To Address '127.0.0.1:7817': SE_EADDRINUSE
[2024.09.10-17.05.51:133][  0]LogHttpListener: Warning: HttpListener unable to set desired buffer size (524288): Limited to 425984
[2024.09.10-17.05.51:133][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7817
[2024.09.10-17.05.51:134][  0]LogServer: Display: Server API listening on '0.0.0.0:7817' (Standalone)
[2024.09.10-17.05.51:134][  0]LogServer: Display: Server API listening on '[::]:7817' (Standalone)
[2024.09.10-17.05.51:135][  0]LogGame: MaxNumBackupsaves: 25
[2024.09.10-17.05.51:136][  0]LogLoad: Loading WwiseSoundEngine module: WwiseSoundEngine
[2024.09.10-17.05.51:136][  0]LogInit: Display: Game Engine Initialized.
[2024.09.10-17.05.51:136][  0]LogNetVersion: Set ProjectVersion to ++FactoryGame+rel-main-1.0.0-CL-365306. Version Checksum will be recalculated on next use.
[2024.09.10-17.05.51:138][  0]LogInit: OnPostEngineInit has been broadcasted successfully.
[2024.09.10-17.05.51:140][  0]LogInit: Display: Starting Game.
[2024.09.10-17.05.51:140][  0]LogNet: Browse: /Game/FactoryGame/Map/DedicatedserverEntry?Name=Player?listen
[2024.09.10-17.05.51:141][  0]LogLoad: LoadMap: /Game/FactoryGame/Map/DedicatedserverEntry?Name=Player?listen
[2024.09.10-17.05.51:141][  0]LogWorld: BeginTearingDown for /Temp/Untitled_0
[2024.09.10-17.05.51:141][  0]LogWorld: UWorld::CleanupWorld for Untitled, bSessionEnded=true, bCleanupResources=true
[2024.09.10-17.05.51:145][  0]LogStreaming: Display: 0.007 ms for processing 108 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 20 (1270->1250) packages and 39 (1997->1958) public exports.
[2024.09.10-17.05.51:149][  0]LogUObjectHash: Compacting FUObjectHashTables data took   1.54ms
[2024.09.10-17.05.51:161][  0]LogChaos: FPhysicsSolverBase::AsyncDt:-1.000000
[2024.09.10-17.05.51:162][  0]LogAIModule: Creating AISystem for world DedicatedserverEntry
[2024.09.10-17.05.51:163][  0]LogLoad: Game class is 'BP_GameModeMenu_C'
[2024.09.10-17.05.51:171][  0]LogReplicationGraph: Display: SetActorDiscoveryBudget set to 20 kBps (5333 bits per network tick).
[2024.09.10-17.05.51:171][  0]LogNetCore: DDoS detection status: detection enabled: 0 analytics enabled: 0
[2024.09.10-17.05.51:171][  0]LogInit: BSD IPv4/6: Socket queue. Rx: 262144 (config 131072) Tx: 262144 (config 131072)
[2024.09.10-17.05.51:171][  0]LogInit: BSD IPv4/6: Socket queue. Rx: 262144 (config 131072) Tx: 262144 (config 131072)
[2024.09.10-17.05.51:171][  0]LogNet: Created socket for bind address: 0.0.0.0:0
[2024.09.10-17.05.51:171][  0]PacketHandlerLog: Loaded PacketHandler component: DTLSHandlerComponent ()
[2024.09.10-17.05.51:171][  0]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2024.09.10-17.05.51:171][  0]PacketHandlerLog: Loaded PacketHandler component: FactoryDedicatedServer.DSQueryHandlerComponentFactory (DSQueryHandlerComponent)
[2024.09.10-17.05.51:171][  0]LogNet: GameNetDriver FGDSIpNetDriver_2147482293 IpNetDriver listening on port 7817
[2024.09.10-17.05.51:171][  0]LogWorld: Bringing World /Game/FactoryGame/Map/DedicatedserverEntry.DedicatedserverEntry up for play (max tick rate 30) at 2024.09.10-17.05.51
[2024.09.10-17.05.51:181][  0]LogGame: Discovered 0 Remote Call Objects on AFGGameMode::InitGame
[2024.09.10-17.05.51:182][  0]LogWorld: Bringing up level for play took: 0.010842
[2024.09.10-17.05.51:182][  0]LogGameMode: Display: Match State Changed from EnteringMap to WaitingToStart
[2024.09.10-17.05.51:182][  0]LogGame: Apply Lightweight Instances from Load took: 0.000000 seconds
[2024.09.10-17.05.51:203][  0]LogGameState: Match State Changed from EnteringMap to WaitingToStart
[2024.09.10-17.05.51:203][  0]LogLoad: Took 0.062311 seconds to LoadMap(/Game/FactoryGame/Map/DedicatedserverEntry)
[2024.09.10-17.05.51:204][  0]LogGame: Telemetry, starting service.
[2024.09.10-17.05.51:204][  0]LogGame: Warning: Telemetry, no local player found.
[2024.09.10-17.05.51:204][  0]LogGame: Telemetry instance started without a platform.
[2024.09.10-17.05.51:210][  0]LogInit: Display: Engine is initialized. Leaving FEngineLoop::Init()
[2024.09.10-17.05.51:210][  0]LogLoad: (Engine Initialization) Total time: 1.72 seconds
[2024.09.10-17.05.51:243][  0]LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled
[2024.09.10-17.05.52:579][ 40]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
[2024.09.10-17.06.02:595][340]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
[2024.09.10-17.06.12:612][640]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
[2024.09.10-17.06.19:457][845]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
[2024.09.10-17.06.19:557][848]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
[2024.09.10-17.06.19:658][851]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
[2024.09.10-17.06.21:294][900]LogServer: Display: Server startup time elapsed and saving/level loading is done, auto-pause is allowed to proceed from now on (if enabled in server settings). WorldTimeSeconds = 30.08
[2024.09.10-17.06.32:112][224]LogNet: NotifyAcceptingConnection accepted aggregation: 192.168.0.39:62326 (123)
[2024.09.10-17.06.32:146][225]LogNet: NotifyAcceptingConnection accepted from: 192.168.0.39:62326
```

**Comment by wolveix** [comment]
@EuleMitKeule  Remove `SERVERIP`, update your image

**Comment by MegaShinySnivy** [comment]
> nope, no network=host is used, service is exposed as LoadBalancer and only on 7777:
> 
> ![image](https://private-user-images.githubusercontent.com/46779261/366135931-ce861b21-cefb-4eb9-9556-a6c9a31b25c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODc5NDQsIm5iZiI6MTcyNTk4NzY0NCwicGF0aCI6Ii80Njc3OTI2MS8zNjYxMzU5MzEtY2U4NjFiMjEtY2VmYi00ZWI5LTk1NTYtYTZjOWEzMWIyNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE3MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2YwYmE5YTVhYTg0MDM4YTNhOTc4ODA0YmE2YTVjNjlkNDY3ODFlOTQ1NWE1ODgxMDJhOTQwMjI3ZGY3MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4xf1nhAE3V9eS3XI9j4Rl9Kd3xhOdsYv8a1eWo_rU9E)

How are you doing both TCP and UDP on a single service? Last I checked that isn't possible.

**Comment by wolveix** [comment]
Update from my conversation with the Coffee Stain dev:

It seems there's an issue with how the TCP bind disregards multihoming. You can reproduce the issue we see with the container by running it on baremetal with -multihome set to anything. No, we are not using -multihome within the container. Yes, this is an issue we need to wait for them to fix.

**Comment by 98jan** [comment]
> > nope, no network=host is used, service is exposed as LoadBalancer and only on 7777:
> > ![image](https://private-user-images.githubusercontent.com/46779261/366135931-ce861b21-cefb-4eb9-9556-a6c9a31b25c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODc5NDQsIm5iZiI6MTcyNTk4NzY0NCwicGF0aCI6Ii80Njc3OTI2MS8zNjYxMzU5MzEtY2U4NjFiMjEtY2VmYi00ZWI5LTk1NTYtYTZjOWEzMWIyNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE3MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkM2YwYmE5YTVhYTg0MDM4YTNhOTc4ODA0YmE2YTVjNjlkNDY3ODFlOTQ1NWE1ODgxMDJhOTQwMjI3ZGY3MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4xf1nhAE3V9eS3XI9j4Rl9Kd3xhOdsYv8a1eWo_rU9E)
> 
> How are you doing both TCP and UDP on a single service? Last I checked that isn't possible.

As stated here: https://ben-lab.github.io/kubernetes-UDP-TCP-bug-same-port/ an existing service can't be updated, but as long as you create a new service, both tcp and udp can be applied to the same port e.g.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: satisfactory
    meta.helm.sh/release-namespace: satisfactory
  labels:
    app.kubernetes.io/instance: satisfactory
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/version: v1.6.1
    helm.sh/chart: satisfactory-0.1.3
    helm.toolkit.fluxcd.io/name: satisfactory
    helm.toolkit.fluxcd.io/namespace: satisfactory
  name: satisfactory
  namespace: satisfactory
spec:
  externalIPs:
  - <externalIP>
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: game-port
    port: 7777
    protocol: UDP
    targetPort: 7777
  - name: game-port-tcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    app.kubernetes.io/instance: satisfactory
    app.kubernetes.io/name: satisfactory
  sessionAffinity: None
  type: LoadBalancer
```

If you have a baremetal cluster you need to set the externalIP, I am using cilium and it does automatically forward the traffic for me.

**Comment by EuleMitKeule** [comment]
@wolveix Exact same problem after updating the image and removing `SERVERIP`. With our without the modified `exec` statement.

**Comment by sarcasticgoat** [comment]
I managed to get local connections and NAT'd connections working by using the workaround from @cheGGo (https://github.com/wolveix/satisfactory-server/issues/260#issuecomment-2341472577) and also adding my public IP to the run.sh directly
`exec ./FactoryServer.sh -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" "<publicIPaddress>"
`
![image](https://github.com/user-attachments/assets/9d0fcf75-e727-4548-955e-14724453fb33)
![image](https://github.com/user-attachments/assets/50d51eaa-1a1f-4c6f-8dd6-01b6b10e0c9d)

**Comment by DominikUrban** [comment]
It seems to be due to IPv6, after I activated IPv6 for my Docker container it works without the host mode:

`services:
  stable:
    image: 'wolveix/satisfactory-server:dev'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './config:/config'
    environment:
      - SERVERGAMEPORT=7777
      - SERVERIP=
    restart: unless-stopped
#    network_mode: 'host'
    networks:
      - ip6net

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64`

**Comment by EuleMitKeule** [comment]
@sarcasticgoat You might want to remove that screenshot, as it contains sensitive data

**Comment by wolveix** [comment]
@DominikUrban bingo.

The dev said they're hoping to release a patch on Wednesday/Thursday

**Comment by DominikUrban** [comment]
@wolveix I only found out about it through your posts with the devs ;)

But it could help those who cannot use host mode, e.g. with Docker Swarm

**Comment by daniel5gh** [comment]
@wolveix  Another change that is important to realize is that game saves appear to be in a different location, I've mounted it like so:

```
'/home/redacted/satis/SaveGames:/home/ubuntu/.config/Epic/FactoryGame/Saved/SaveGames'
```

it will create the `ServerSettings.7777.sav` there as well which will have the server password and all that (self signed cert too perhaps). I've moved my saves into `/home/redacted/satis/SaveGames/server` and I am up and running in my old game.

The ports don't seem to be an issue for me, I am running on podman rootless and I forward/open 7777 on tcp and udp. https apo and udp is working just fine.

**Comment by wolveix** [comment]
@daniel5gh yeah, I know. I'll look into the directory issue shortly

**Comment by EuleMitKeule** [comment]
> But it could help those who cannot use host mode, e.g. with Docker Swarm

I have never used IPv6 with Docker and I don't think it works at all on my server, so not for me unfortunately.
All the other workarounds also do not work for me for some reason.

**Comment by BadWolf97** [comment]
@DominikUrban s Solution works for me as well, without using any namespaces or anything else.

**Comment by jeliasson** [comment]
As per @DominikUrban suggestion, is this seems to be working fine on my end. 
Can anyone else confirm?

```yml
services:
  satisfactory:
    restart: unless-stopped
    container_name: satisfactory
    image: wolveix/satisfactory-server:latest
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/<redacted>/docker/satisfactory/data:/config:rw
    environment:
      PUID: '1000'
      PGID: '1000'
      MAXPLAYERS: '6'
      STEAMBETA: 'false'
      AUTOPAUSE: 'false'
      AUTOSAVEINTERVAL: 1800
      AUTOSAVENUM: 48
      AUTOSAVEONDISCONNECT: 'true'
      CRASHREPORT: 'true'
      MAXOBJECTS: 2162688
      MAXTICKRATE: 60
      NETWORKQUALITY: 3
      SKIPUPDATE: 'false'
      ROOTLESS: 'false'
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 10G
    networks:
      - satisfactory

networks:
  satisfactory:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
```

**Comment by 1n5aN1aC** [comment]
@jeliasson Yes, that config with the ipv6 network (no host networking) is working for me as a stop-gap solution.

However, as @daniel5gh mentioned, the saves have moved to a new location, and at a minimum those would need mapped outside the container as well.

**Comment by shredoo** [comment]
> For those on docker-compose, that is `network_mode: 'host'`, server works fine for me with this workaround.

where do you put this in the yml

**Comment by wolveix** [comment]
@shredoo you can remove the port declarations as they do nothing while `net=host`; however, I recommend leaving them there as you'll want to remove `net=host` once Coffee Stain have straightened this out.

```
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        network_mode: host
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - './satisfactory-server:/config'
        environment:
            MAXPLAYERS: 4
            PGID: 1000
            PUID: 1000
            ROOTLESS: false
            STEAMBETA: false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 6G
            reservations:
              memory: 4G
```

**Comment by 1n5aN1aC** [comment]
To recap recent discoveries, The following config appears to be fully working *without host networking mode* for those using *docker compose*:

**NOTE:  THIS IS NOT A FINAL SOLUTION FOR SEVERAL REASONS  
Only do this if you need to be running now, and realize you will have to change stuff later.**
- This is saving your saves into a temp folder you will probably have to manually move files once Satisfactory updates, and the container is updated.
- This is enabling ipv6 on a docker network solely for Satisfactory.  I don't think this is fully portable, and will likely not work on some systems, depending on your network setup.

```
  satisfactory:
    container_name: satisfactory
    image: wolveix/satisfactory-server
    restart: unless-stopped
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
    volumes:
      - /path_goes_here/satisfactory:/config
      - /path_goes_here/satisfactory/tempSaves:/home/ubuntu/.config/Epic/FactoryGame/Saved/SaveGames
    environment:
      - PGID=1000
      - PUID=1000
      - AUTOSAVEONDISCONNECT=true
    networks:
      - satisfactory
networks:
  satisfactory:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64
```

**Comment by TOoSmOotH** [comment]
>     ipam:
>       config:
>         - subnet: 2001:db8::/64
> ```

Are you still connecting to it over ipv4?

**Comment by wolveix** [comment]
Yes, though it requires v6 in the first place. I'll update the top of this issue with both this solution, and `net=host` so people are aware. Thank you!

I've spent the last few hours constantly typing and trying to resolve this issue and working with all of you, so I'm going to take a break. I just pushed a fix for the issue where save data wasn't persisting, please make sure you're all running the latest image. Thanks!

**Comment by JoshuaVandaele** [comment]
For people using reverse proxies/etc, instead of net=host a macvlan also works perfectly

**Comment by EuleMitKeule** [comment]
The IPv6 network works for me, I connect via the IPv4 address as before.

**Comment by wolveix** [comment]
@JoshuaVandaele yes, as you're effectively connecting the container directly to the network. Essentially, anything to remove the firewall (if you'd like to call it that) around a container should resolve the issue (as you're giving full access to the network interface on the container)

**Comment by Acekorneya** [comment]
> @shredoo you can remove the port declarations as they do nothing while `net=host`; however, I recommend leaving them there as you'll want to remove `net=host` once Coffee Stain have straightened this out.
> 
> ```
> services:
>     satisfactory-server:
>         container_name: 'satisfactory-server'
>         hostname: 'satisfactory-server'
>         image: 'wolveix/satisfactory-server:latest'
>         network_mode: host
>         ports:
>             - '7777:7777/udp'
>             - '7777:7777/tcp'
>         volumes:
>             - './satisfactory-server:/config'
>         environment:
>             MAXPLAYERS: 4
>             PGID: 1000
>             PUID: 1000
>             ROOTLESS: false
>             STEAMBETA: false
>         restart: unless-stopped
>         deploy:
>           resources:
>             limits:
>               memory: 6G
>             reservations:
>               memory: 4G
> ```

This Fix the Issue for sure when using docker compose

**Comment by wolveix** [comment]
Appreciate the love @erockFTW :) My fingers have not stopped typing in hours 😆 Working on another patch to improve the image a little, then I'll probably call it for today.

**Comment by Kuroo2021** [comment]
Very much thank you a bunch, @wolveix. We can give you crazy times, but it just shows the love for this game and the love that you show back. Thank you kindly for everything you have done and will do!

**Comment by toobigtoofail** [comment]
I am still having issues and I think it might be related to the IPv6 stuff (although I am uncertain).

I am hosting the server on an AWS EC2 using VPC and Elastic IP.  Everything is setup with IPv4 (no IPv6 enabled).

Does this update mean I need to now redo the whole setup with IPv6?

**Comment by wolveix** [comment]
@toobigtoofail just wait until the fix is released honestly, it's not worth the hassle on AWS in my opinion :) It should be fixed tomorrow/in a couple of days

**Comment by opticalgenesis** [comment]
Quick q if I may for those that got it working; I have also (IPV6 method) but my friends are unable to connect remotely. Have any of you lot got other, remote connections to work? Or local only? If not, will not waste any more time on it and just wait for the CSS fix

**Comment by daniel5gh** [comment]
> Quick q if I may for those that got it working; I have also (IPV6 method) but my friends are unable to connect remotely. Have any of you lot got other, remote connections to work? Or local only? If not, will not waste any more time on it and just wait for the CSS fix

It should work on remote connections too. Everyone's setup is slightly different, but make sure to check firewall on the host (and upstream routers etc) if it works for some (local) connections but not others. I've been using `curl` to test and assert connections are working, before realizing my cloud provider had another firewall I forgot about.

`curl -kv https://satisfactory.your-domain.test:7777/` and see if you get a connection. If working you will get a 404 response with body

```json
{"errorCode": "errors.com.epicgames.httpserver.route_handler_not_found", "errorMessage": ""}
```

**Comment by ProCakeMan** [comment]
I'm running it like this (from example) with the net=host, but I still get the failed to connect to the API in-game? Is something in my script incorrect?
`docker run \
--net=host \
--detach \
--name=guttas-ronkehi \
--hostname guttas-ronkehi \
--restart unless-stopped \
--volume ./satisfactory-server:/config \
--env MAXPLAYERS=8 \
--env PGID=1000 \
--env PUID=1000 \
--env ROOTLESS=false \
--env STEAMBETA=false \
--memory-reservation=6G \
--memory 12G \
--publish 7777:7777/udp \
--publish 7777:7777/tcp \
wolveix/satisfactory-server:latest
`

**Comment by ZexMaxwell001** [comment]
to acheve this setting for unraid users. just pull the drop down on Network type and select host.
![image](https://github.com/user-attachments/assets/21afbba1-6f3f-452d-a38c-5b08701bd7da)

**Comment by opticalgenesis** [comment]
@daniel5gh @1n5aN1aC thank you both legends, had changed the port to TCP/UDP on the Nest router but not on the internet gateway; works perfectly now thanks both

**Comment by Ikariusrb** [comment]
@wolveix  - Thank you, the workaround appears to work locally, but unfortunately something additional seems to be necessary in order to configure firewall port mapping.  Everything was working perfectly prior to 1.0.  I have updated my docker compose file to use "host" networking, and it works internally.   I updated my firewall port-mapping to map 7777 to both TCP and UDP to the host running the docker container, and unfortunately, when I attempt to connect by going out a VPN to come back in, I end up with "Failed to connect to the Server API" error.     I'm happy to test any configuration changes available.

Thanks!

**Comment by daniel5gh** [comment]
> Failed to connect to the Server API

From what I've seen today when I was facing connection issues, it looked like this particular message shows when the 7777/UDP connection is fine but the 7777/TCP connection can't be established.
This matches with your description saying pre-1.0 everything was ok, so you have 7777/UDP configured to accept connections from wherever you are connecting from, but then TCP appears to still be blocked.
When the UDP connection is not established the message was something like "Server is offline" instead.
If you can, double check if you can reach the HTTP API using a browser or curl. If you can connect from the host where the container is running but not anywhere else then the container is behaving properly, and it's likely a firewall or some other issue with your specific set up.

**Comment by pcire** [comment]
Just a hint for anyone, who got this problem and can't connect to the server, after using the "host"-fix: docker (or docker-compose) opens ports in your firewall automatically for all mapped ports. With the "host"-option you have to open the ports yourself (iptables, ufw, etc.). This took me several hours to figure out >_>

**Comment by sirber** [comment]
> Just a hint for anyone, who got this problem and can't connect to the server, after using the "host"-fix: docker (or docker-compose) opens ports in your firewall automatically for all mapped ports. With the "host"-option you have to open the ports yourself (iptables, ufw, etc.). This took me several hours to figure out >_>

thank you!! :D 

```bash
sudo firewall-cmd --permanent --add-port=7777/tcp
sudo firewall-cmd --permanent --add-port=7777/udp
sudo firewall-cmd --reload
```

then I had to claim the new server, reload the game from a save file.

**Comment by sirber** [comment]
perfect!

![20240910164223_1](https://github.com/user-attachments/assets/26500cde-cbd3-4ec9-89d6-8b9038ae23c4)

**Comment by markusressel** [comment]
@daniel5gh
> If you can, double check if you can reach the HTTP API using a browser or curl.

Where should this API be located?
```
curl -L http://<server-ip>:7777
```
doesn't get me anything, not even within the docker container (using `127.0.0.1` as the IP)

**Comment by ankemp** [comment]
@wolveix You should lock this issue, its gone way off the rails.

**Comment by LevantinLynx** [comment]
```bash
[2024.09.10-20.50.12:882][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7777
[2024.09.10-20.50.12:883][  0]LogServer: Display: Server API listening on '0.0.0.0:7777' (Standalone)
```
This seams to be the problem. The tcp port always binds on 127.0.0.1, while ufp correctly binds to 0.0.0.0

This also happens if one explicitly sets the `SERVERIP: '0.0.0.0'`. Even if network_mode is set to host...
![image](https://github.com/user-attachments/assets/cd977ea7-5284-40e6-b8dd-34ce0bc610db)

**Comment by wolveix** [comment]
It has a little, but I'm fine with leaving it for general discussion.

Please do try to keep the conversation inline with connectivity issues. Game bugs shouldn't really be brought up here, as there's nothing any of us can do about it :)

Not to mention, I suspect many people are watching this thread waiting for a fix. So let's be mindful.

**Comment by wolveix** [comment]
> ```bash
> [2024.09.10-20.50.12:882][  0]LogHttpListener: Created new HttpListener on 127.0.0.1:7777
> [2024.09.10-20.50.12:883][  0]LogServer: Display: Server API listening on '0.0.0.0:7777' (Standalone)
> ```
> This seams to be the problem. The tcp port always binds on 127.0.0.1, while udp correctly binds to 0.0.0.0
> 
> This also happens if one explicitly sets the `SERVERIP: '0.0.0.0'`. Even if network_mode is set to host...
> ![image](https://github.com/user-attachments/assets/cd977ea7-5284-40e6-b8dd-34ce0bc610db)
> 

No, once again, both of these issues have been addressed countless times today. Coffee Stain confirmed that the 127.0.0.1 bind is irrelevant, and the SERVERIP variable has been removed from the image. It only served the `multihome` parameter, which was already deprecated. Please read the opening issue, where I directly explain what Coffee Stain and I were able to determine the issue to be :)

**Comment by daniel5gh** [comment]
> ```
> curl -L http://<server-ip>:7777
> ```
it should be https. add `-v` for more info and `-k` to accept self signed cert.

This is the last reply from me here today. It's not that I'm not willing to help out, and while I think this helps multiple people debug their setups, as wolveix mentioned peeps are watching this thread and I don't want to spam semi-unrelated notifications.

**Comment by wolveix** [comment]
Coffee Stain have now identified the underlying issue, and will release a patch tomorrow 🎉

**Comment by wolveix** [comment]
We have a fix!! Pushing the code now!

**Comment by wolveix** [comment]
This issue should now be closed 🎉

Please read the opening issue to ensure that you're running the latest image before reporting that things aren't working for you. Thanks!

**Comment by Zblocker64** [comment]
Verified I am running correct image, still same error. Running on k8s. Maybe this?

```LogNet: Created socket for bind address: 0.0.0.0:0```

**Comment by LevantinLynx** [comment]
And the fix is literally to bind the tcp port to any... `[HTTPServer.Listeners]:DefaultBindAddress=any`

**Comment by Zblocker64** [comment]
> And the fix is literally to bind the tcp port to any... `[HTTPServer.Listeners]:DefaultBindAddress=any`

That's why I said maybe.

**Comment by wolveix** [comment]
@Zblocker64 please open a new issue and fill out the issue template, curious as to what the issue could be! Did you allow both TCP and UDP through for your custom port in your service/ingress files?

**Comment by kivle** [comment]
> This issue should now be closed 🎉
> 
> Please read the opening issue to ensure that you're running the latest image before reporting that things aren't working for you. Thanks!

Can verify that the fix immediately worked for me. Thanks for all the effort to get things working. :)

**Comment by Zblocker64** [comment]
> @Zblocker64 please open a new issue and fill out the issue template, curious as to what the issue could be! Did you allow both TCP and UDP through for your custom port in your service/ingress files?

I can do that. Yes I did

**Comment by Sociopathssive** [comment]
> This issue should now be closed 🎉
> 
> Please read the opening issue to ensure that you're running the latest image before reporting that things aren't working for you. Thanks!

Thanks you for all the work to drill down to resolve the issue, looking forward to the applied fixes in a day or so!

**Comment by wolveix** [comment]
@Sociopathssive to be clear, it works 100% right now :) The fix Coffee Stain should release tomorrow will remove the necessity for the current workaround in our launch parameters

**Comment by tlewis17** [comment]
Works for me too. Also, one note for anyone like me, I had previously mapped multiple TCP/UDP ports as per an older version of the documentation back when I had originally set up my server. When updating to this new version you need to make sure you map 7777 on both TCP and UDP.

**Comment by pixelwave** [comment]
_"Could not connect to the server. Failed to connect to the Server API"_

Same issue here ... running Pterodactyl VM on Proxmox Server. Version 0.8 was all fine ... now with 1.0 I have the same error message. Will there be a server update in the next days or do I have to fix configuration manually because of the IP6 issue?

**Comment by Tuumke** [comment]
Another fix is to bind port 7778 in addition to port 7777 to the container.
```
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
            - '7778:7778/udp'
            - '7778:7778/tcp'
```

**Comment by Regtervegter** [comment]
I keep reading about the issue on docker but i am running my server on windows and im getting the same issue when trying to remotely connect to my server, but locally i can connect? Not sure if im missing anything on my router even though it used to work before the update? I have allowed UDP 15777 7777 and 15000 via my router.

**Comment by wolveix** [comment]
@pixelwave you need to update your image. This has been fixed already.

@Regtervegter that's the game bug that will be patched by Coffee Stain tomorrow. But for clarity, you JUST need port 7777/tcp AND port 7777/udp. You can circumvent the bug using the launch param you can see in our `run.sh` file (on the last line)

**Comment by wolveix** [comment]
@Tuumke no, again, this does not fix the underlying issue. Update to the latest image, and everything is fixed :)

**Comment by wolveix** [comment]
FOR ANYONE ELSE THAT STUMBLES ACROSS THIS:

If you're still experiencing API connectivity issues, you just need to update the image. You can manually change from:
`wolveix/satisfactory-server:latest`
To:
`wolveix/satisfactory-server:1.7.3`

You also need to ensure that BOTH ports 7777/udp AND 7777/tcp are port forwarded etc. You do not need ANY other ports.

If you see issues about the port binding in the log file, Coffee Stain confirmed to me that these messages are meaningless, please disregard them. The same goes for the certificate being self-signed. If you're getting a certificate key missing error when trying to join, make sure you've added the server through the in-game server manager FIRST.
