### ISSUE TITLE
segmentation fault on start

### ISSUE THREAD

**Issue by indietyp** [wolveix/satisfactory-server#61]
**Describe the Bug**
whenever the server is started I am getting a segmentation fault of the game. I am unsure if this is due to the image or due to the game server itself.

**Your Runtime Command or Docker Compose File**
```
docker run -d -v <REDACTED>:/config -e DEBUG=false -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e SKIPUPDATE=false -e STEAMBETA=true --restart unless-stopped -p '7777:7777/udp' -p '15000:15000/udp' -p '15777:15777/udp' --name satisfactory-2021-10 wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

... taken from `lsb_release -a`

**Additional Context**
```
Setting max players to 4
Experimental flag is set. Experimental will be downloaded instead of Early Access.
Checking available space...423GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x11) preallocating, progress: 8.29 (373884973 / 4508056194)
 Update state (0x61) downloading, progress: 2.85 (128313646 / 4508056194)
 Update state (0x61) downloading, progress: 15.19 (684592421 / 4508056194)
 Update state (0x61) downloading, progress: 26.60 (1199008194 / 4508056194)
 Update state (0x61) downloading, progress: 37.01 (1668265204 / 4508056194)
 Update state (0x61) downloading, progress: 48.49 (2185821849 / 4508056194)
 Update state (0x61) downloading, progress: 60.49 (2726943025 / 4508056194)
 Update state (0x61) downloading, progress: 74.46 (3356633046 / 4508056194)
 Update state (0x61) downloading, progress: 87.07 (3925277091 / 4508056194)
 Update state (0x61) downloading, progress: 99.29 (4476132090 / 4508056194)
 Update state (0x81) verifying update, progress: 4.13 (186107407 / 4508056194)
 Update state (0x81) verifying update, progress: 16.31 (735348870 / 4508056194)
 Update state (0x81) verifying update, progress: 28.71 (1294370801 / 4508056194)
 Update state (0x81) verifying update, progress: 41.09 (1852492505 / 4508056194)
 Update state (0x81) verifying update, progress: 53.29 (2402355460 / 4508056194)
 Update state (0x81) verifying update, progress: 65.92 (2971768598 / 4508056194)
 Update state (0x81) verifying update, progress: 78.44 (3536042920 / 4508056194)
 Update state (0x81) verifying update, progress: 90.69 (4088255487 / 4508056194)
Success! App '1690800' fully installed.
Project file not found: /config/gamefiles/FactoryGame/FactoryGame.uproject
sh: 1: xdg-user-dir: not found
4.26.1-170636+++FactoryGame+main 522 3
Disabling core dumps.
LogInit: Display: Running engine for game: FactoryGame
LogInit: Display: Project file not found: /config/gamefiles/FactoryGame/FactoryGame.uproject
LogInit: Display: 	Attempting to find via project info helper.
LogUProjectInfo: Found projects:
LogPakFile: Display: Found Pak file ../../../FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak attempting to mount.
LogPakFile: Display: Mounting pak file ../../../FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak.
LogPakFile: PakFile PrimaryIndexSize=586698
LogPakFile: PakFile PathHashIndexSize=670088
LogPakFile: PakFile FullDirectoryIndexSize=1859590
LogPakFile: OnPakFileMounted2Time == 0.000001
LogPlatformFile: Using cached read wrapper
LogTaskGraph: Started task graph with 4 named threads and 8 total threads with 1 sets of task threads.
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +0:00, Platform Override: ''
LogPluginManager: Mounting plugin ReplicationGraph
LogPluginManager: Mounting plugin DTLSHandlerComponent
LogPluginManager: Mounting plugin Wwise
LogPluginManager: Mounting plugin GeometryMode
LogPluginManager: Mounting plugin ApexDestruction
LogPluginManager: Mounting plugin BlueprintStats
LogPluginManager: Mounting plugin OnlineFramework
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin LensDistortion
LogPluginManager: Mounting plugin WindowsDeviceProfileSelector
LogPluginManager: Mounting plugin SteamController
LogPluginManager: Mounting plugin SteamShared
LogPluginManager: Mounting plugin RawInput
LogPluginManager: Mounting plugin MfMedia
LogPluginManager: Mounting plugin OnlineSubsystemSteam
LogPluginManager: Mounting plugin OnlineSubsystemEOS
LogPluginManager: Mounting plugin SignificanceManager
LogPluginManager: Mounting plugin PythonScriptPlugin
LogPluginManager: Mounting plugin EditorScriptingUtilities
LogPluginManager: Mounting plugin EditorTests
LogPluginManager: Mounting plugin FbxAutomationTestBuilder
LogPluginManager: Mounting plugin FunctionalTestingEditor
LogPluginManager: Mounting plugin RuntimeTests
LogPluginManager: Mounting plugin ScreenshotTools
LogPluginManager: Mounting plugin CSSEditorToolsExtension
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin EnvironmentQueryEditor
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin AnimationSharing
LogPluginManager: Mounting plugin PluginUtils
LogPluginManager: Mounting plugin PropertyAccessEditor
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin AutomationUtils
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin ChaosClothEditor
LogPluginManager: Mounting plugin ChaosCloth
LogPluginManager: Mounting plugin ChaosEditor
LogPluginManager: Mounting plugin PlanarCut
LogPluginManager: Mounting plugin GeometryProcessing
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin GeometryCollectionPlugin
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin ChaosSolverPlugin
LogPluginManager: Mounting plugin ChaosNiagara
LogPluginManager: Mounting plugin Niagara
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin MotoSynth
LogPluginManager: Mounting plugin PlatformCrypto
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin MeshPainting
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin TemplateSequence
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin AssetTags
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin ChunkDownloader
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin GooglePAD
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin SoundFields
LogPluginManager: Mounting plugin Synthesis
LogPluginManager: Mounting plugin AudioSynesthesia
LogInit: Using libcurl 7.65.3-DEV
LogInit:  - built for x86_64-unknown-linux-gnu
LogInit:  - supports SSL with OpenSSL/1.1.1c
LogInit:  - supports HTTP deflate (compression) using libz 1.2.8
LogInit:  - other features:
LogInit:      CURL_VERSION_SSL
LogInit:      CURL_VERSION_LIBZ
LogInit:      CURL_VERSION_IPV6
LogInit:      CURL_VERSION_ASYNCHDNS
LogInit:      CURL_VERSION_LARGEFILE
LogInit:      CURL_VERSION_TLSAUTH_SRP
LogInit:  CurlRequestOptions (configurable via config and command line):
LogInit:  - bVerifyPeer = true  - Libcurl will verify peer certificate
LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
LogInit:  - MaxHostConnections = 16  - Libcurl will limit the number of connections to a host
LogInit:  - LocalHostAddr = Default
LogInit:  - BufferSize = 65536
Shutdown handler: initalize.
LogOnline: OSS: Creating online subsystem instance for: EOS
LogOnline: OSS: FOnlineSubsystemEOS: Init success.
LogSteamShared: Display: Loading Steam SDK 1.47
LogCore: Warning: dlopen failed: /config/gamefiles/Engine/Binaries/Linux/libsteam_api.so: cannot open shared object file: No such file or directory
LogSteamShared: Warning: Could not find system one, loading bundled libsteam_api.so.
LogSteamShared: Display: Loaded libsteam_api.so at 0xc2d550
LogSteamShared: Steam SDK Loaded!
LogOnline: OSS: Creating online subsystem instance for: STEAM
LogOnline: Warning: STEAM: Steam API failed to initialize!
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: OSS: Unable to create OnlineSubsystem module STEAM
LogOnline: OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for module [EOS]
LogOnline: OSS: Creating online subsystem instance for: STEAM
LogOnline: Warning: STEAM: Steam API failed to initialize!
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogInit: Build: ++FactoryGame+main-CL-170636
LogInit: Engine Version: 4.26.1-170636+++FactoryGame+main
LogInit: Compatible Engine Version: 4.26.1-170636+++FactoryGame+main
LogInit: Net CL: 170636
LogInit: OS: GenericOSVersionLabel (GenericOSSubVersionLabel), CPU: AMD Ryzen 5 3600 6-Core Processor              , GPU: GenericGPUBrand
LogInit: Compiled (64-bit): Oct 18 2021 21:21:12
LogInit: Compiled with Clang: 10.0.1 (https://github.com/llvm/llvm-project ef32c611aa214dea855364efd7ba451ec5ec3f74)
LogInit: Build Configuration: Shipping
LogInit: Branch Name: ++FactoryGame+main
LogInit: Command Line:  -log -NoSteamClient -unattended
LogInit: Base Directory: /config/gamefiles/Engine/Binaries/Linux/
LogInit: Allocator: binned2
LogInit: Installed Engine Build: 0
LogInit: Launcher File: /config/gamefiles/launcher_id
LogInit: Launcher ID: 
LogInit: Launcher Artifact: 
LogInit: Presizing for max 2097152 objects, including 1 objects not considered by GC, pre-allocating 0 bytes for permanent pool.
LogStreaming: Display: Async Loading initialized: Event Driven Loader: true, Async Loading Thread: false, Async Post Load: false
LogInit: Object subsystem initialized
[2021.10.30-16.10.16:997][  0]LogLinux: Selected Device Profile: [LinuxServer]
[2021.10.30-16.10.16:997][  0]LogInit: Applying CVar settings loaded from the selected device profile: [LinuxServer]
[2021.10.30-16.10.16:997][  0]LogHAL: Display: Platform has ~ 4 GB [67439095808 / 4294967296 / 63], which maps to Smallest [LargestMinGB=32, LargerMinGB=12, DefaultMinGB=8, SmallerMinGB=6, SmallestMinGB=0)
[2021.10.30-16.10.16:997][  0]LogInit: Going up to parent DeviceProfile [Linux]
[2021.10.30-16.10.16:997][  0]LogInit: Going up to parent DeviceProfile []
[2021.10.30-16.10.16:997][  0]LogInit: Unix hardware info:
[2021.10.30-16.10.16:997][  0]LogInit:  - we are the first instance of this executable
[2021.10.30-16.10.16:997][  0]LogInit:  - this process' id (pid) is 107, parent process' id (ppid) is 22
[2021.10.30-16.10.16:997][  0]LogInit:  - we are not running under debugger
[2021.10.30-16.10.16:997][  0]LogInit:  - machine network name is '76f27002ed9c'
[2021.10.30-16.10.16:997][  0]LogInit:  - user name is 'steam' (steam)
[2021.10.30-16.10.16:997][  0]LogInit:  - we're logged in locally
[2021.10.30-16.10.16:997][  0]LogInit:  - we're running without rendering
[2021.10.30-16.10.16:997][  0]LogInit:  - CPU: AuthenticAMD 'AMD Ryzen 5 3600 6-Core Processor              ' (signature: 0x870F10)
[2021.10.30-16.10.16:997][  0]LogInit:  - Number of physical cores available for the process: 6
[2021.10.30-16.10.16:997][  0]LogInit:  - Number of logical cores available for the process: 12
[2021.10.30-16.10.16:997][  0]LogInit:  - Cache line size: 64
[2021.10.30-16.10.16:997][  0]LogInit:  - Memory allocator used: binned2
[2021.10.30-16.10.16:997][  0]LogInit:  - This binary is optimized with LTO: no, PGO: no, instrumented for PGO data collection: no
[2021.10.30-16.10.16:997][  0]LogInit:  - This is a licensee build.
[2021.10.30-16.10.16:997][  0]LogCore: Benchmarking clocks:
[2021.10.30-16.10.16:997][  0]LogCore:  - CLOCK_MONOTONIC (id=1) can sustain 44432069 (44432K, 44M) calls per second without zero deltas.
[2021.10.30-16.10.16:997][  0]LogCore:  - CLOCK_MONOTONIC_RAW (id=4) can sustain 44394437 (44394K, 44M) calls per second without zero deltas.
[2021.10.30-16.10.16:997][  0]LogCore:  - CLOCK_MONOTONIC_COARSE (id=6) can sustain 206949277 (206949K, 207M) calls per second with 99.999874% zero deltas.
[2021.10.30-16.10.16:997][  0]LogCore: Selected clock_id 1 (CLOCK_MONOTONIC) since it is the fastest support clock without zero deltas.
[2021.10.30-16.10.16:997][  0]LogInit: Unix-specific commandline switches:
[2021.10.30-16.10.16:997][  0]LogInit:  -ansimalloc - use malloc()/free() from libc (useful for tools like valgrind and electric fence)
[2021.10.30-16.10.16:997][  0]LogInit:  -jemalloc - use jemalloc for all memory allocation
[2021.10.30-16.10.16:997][  0]LogInit:  -binnedmalloc - use binned malloc  for all memory allocation
[2021.10.30-16.10.16:997][  0]LogInit:  -filemapcachesize=NUMBER - set the size for case-sensitive file mapping cache
[2021.10.30-16.10.16:997][  0]LogInit:  -useksm - uses kernel same-page mapping (KSM) for mapped memory (OFF)
[2021.10.30-16.10.16:997][  0]LogInit:  -ksmmergeall - marks all mmap'd memory pages suitable for KSM (OFF)
[2021.10.30-16.10.16:997][  0]LogInit:  -preloadmodulesymbols - Loads the main module symbols file into memory (OFF)
[2021.10.30-16.10.16:997][  0]LogInit:  -sigdfl=SIGNAL - Allows a specific signal to be set to its default handler rather then ignoring the signal
[2021.10.30-16.10.16:997][  0]LogInit:  -httpproxy=ADDRESS:PORT - redirects HTTP requests to a proxy (only supported if compiled with libcurl)
[2021.10.30-16.10.16:997][  0]LogInit:  -reuseconn - allow libcurl to reuse HTTP connections (only matters if compiled with libcurl)
[2021.10.30-16.10.16:997][  0]LogInit:  -virtmemkb=NUMBER - sets process virtual memory (address space) limit (overrides VirtualMemoryLimitInKB value from .ini)
[2021.10.30-16.10.16:997][  0]LogInit:  - Physical RAM available (not considering process quota): 63 GB (64314 MB, 65858492 KB, 67439095808 bytes)
[2021.10.30-16.10.16:997][  0]LogInit:  - VirtualMemoryAllocator pools will grow at scale 1.4
[2021.10.30-16.10.16:998][  0]LogInit:  - MemoryRangeDecommit() will will evict the memory from RAM (re-run with -novmapoolevict to change)
[2021.10.30-16.10.17:017][  0]LogInit: Physics initialised using underlying interface: PhysX
[2021.10.30-16.10.17:017][  0]LogInit: Overriding language with engine language configuration option (en-US-Posix).
[2021.10.30-16.10.17:017][  0]LogInit: Overriding language with engine locale configuration option (en-US-Posix).
[2021.10.30-16.10.17:021][  0]LogTextLocalizationResource: LocRes '../../../Engine/Content/Localization/Engine/en-US-POSIX/Engine.locres' could not be opened for reading!
[2021.10.30-16.10.17:021][  0]LogTextLocalizationResource: LocRes '../../../Engine/Plugins/Online/OnlineFramework/Content/Localization/OnlineFramework/en-US-POSIX/OnlineFramework.locres' could not be opened for reading!
[2021.10.30-16.10.17:021][  0]LogTextLocalizationResource: LocRes '../../../Engine/Plugins/Online/OnlineSubsystem/Content/Localization/OnlineSubsystem/en-US-POSIX/OnlineSubsystem.locres' could not be opened for reading!
[2021.10.30-16.10.17:021][  0]LogTextLocalizationResource: LocRes '../../../Engine/Plugins/Online/OnlineSubsystemUtils/Content/Localization/OnlineSubsystemUtils/en-US-POSIX/OnlineSubsystemUtils.locres' could not be opened for reading!
[2021.10.30-16.10.17:021][  0]LogTextLocalizationResource: LocRes '../../../Engine/Plugins/Online/OnlineSubsystemSteam/Content/Localization/OnlineSubsystemSteam/en-US-POSIX/OnlineSubsystemSteam.locres' could not be opened for reading!
[2021.10.30-16.10.17:032][  0]LogRendererCore: Ray tracing is disabled. Reason: r.RayTracing=0.
[2021.10.30-16.10.17:040][  0]LogInit: Overriding language with engine language configuration option (en-US-Posix).
[2021.10.30-16.10.17:040][  0]LogInit: Overriding language with engine locale configuration option (en-US-Posix).
[2021.10.30-16.10.17:044][  0]LogTextLocalizationResource: LocRes '../../../FactoryGame/Content/Localization/Game/en/Game.locres' could not be opened for reading!
[2021.10.30-16.10.17:047][  0]LogTextLocalizationManager: Compacting localization data took   0.44ms
[2021.10.30-16.10.17:115][  0]LogAssetRegistry: FAssetRegistry took 0.0575 seconds to start up
[2021.10.30-16.10.17:156][  0]LogStreaming: Display: FlushAsyncLoading: 1 QueuedPackages, 0 AsyncPackages
[2021.10.30-16.10.17:157][  0]LogPackageLocalizationCache: Processed 23 localized package path(s) for 2 prioritized culture(s) in 0.000086 seconds
[2021.10.30-16.10.17:157][  0]LogPakFile: New pak file ../../../FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak added to pak precacher.
[2021.10.30-16.10.17:160][  0]LogLinux: Selected Device Profile: [LinuxServer]
[2021.10.30-16.10.17:160][  0]LogInit: Active device profile: [0x7f09d8aaa780][0x7f09fa147630 49] LinuxServer
[2021.10.30-16.10.17:160][  0]LogInit: Profiles: [0x7f09d8aaa900][0x7f09fa1489e0 49] Linux, [0x7f09d8aaa780][0x7f09fa147630 49] LinuxServer, 
[2021.10.30-16.10.17:169][  0]LogSerialization: Display: AllowBulkDataInIoStore: 'true'
[2021.10.30-16.10.17:169][  0]LogNetVersion: FactoryGame 1.0.0, NetCL: 170636, EngineNetVer: 16, GameNetVer: 0 (Checksum: 525596976)
[2021.10.30-16.10.17:460][  0]LogActor: Warning: SetReplicates called on non-initialized actor Default__FGSimulatedWheeledVehicle. Directly setting bReplicates is the correct procedure for pre-init actors.
[2021.10.30-16.10.17:521][  0]LogNiagara: Warning: NiagaraSystem /Game/FactoryGame/VFX/Factory/Doors/NS_DoorClose_01.NS_DoorClose_01 IsReadyToRunInternal() failed due to missing SystemScript.  Spawn[<none>] Update[<none>]
[2021.10.30-16.10.18:045][  0]LogPakFile: Precache HighWater 16MB

[2021.10.30-16.10.18:045][  0]LogPakFile: Precache HighWater 32MB

[2021.10.30-16.10.18:045][  0]LogPakFile: Precache HighWater 48MB

[2021.10.30-16.10.18:045][  0]LogPakFile: Precache HighWater 64MB

Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
[2021.10.30-16.10.18:045][  0]LogNiagara: Warning: NiagaraSystem /Game/FactoryGame/VFX/World/AmbientLife/Flies/NS_Fireflies_01.NS_Fireflies_01 IsReadyToRunInternal() failed due to missing SystemScript.  Spawn[<none>] Update[<none>]
[2021.10.30-16.10.18:045][  0]LogNiagara: Warning: NiagaraSystem /Game/FactoryGame/VFX/World/AmbientLife/Bats/NS_Bats_01.NS_Bats_01 IsReadyToRunInternal() failed due to missing SystemScript.  Spawn[<none>] Update[<none>]
[2021.10.30-16.10.18:118][  0]GameAnalyticsModule: Display: GameAnalyticsModule has started!
[2021.10.30-16.10.18:118][  0]LogStreaming: Warning: Failed to read file '../../../FactoryGame/Saved/SaveGames/GameAnalytics.sav' error.
[2021.10.30-16.10.18:203][  0]LogAudioCaptureCore: Display: No Audio Capture implementations found. Audio input will be silent.
[2021.10.30-16.10.18:203][  0]LogAudioCaptureCore: Display: No Audio Capture implementations found. Audio input will be silent.
[2021.10.30-16.10.18:218][  0]LogUObjectArray: 49601 objects as part of root set at end of initial load.
[2021.10.30-16.10.18:218][  0]LogUObjectArray: 2 objects are not in the root set, but can never be destroyed because they are in the DisregardForGC set.
[2021.10.30-16.10.18:218][  0]LogUObjectAllocator: 15768640 out of 0 bytes used by permanent object pool.
[2021.10.30-16.10.18:218][  0]LogUObjectArray: CloseDisregardForGC: 49601/49601 objects in disregard for GC pool
[2021.10.30-16.10.18:219][  0]LogEngine: Initializing Engine...
[2021.10.30-16.10.18:220][  0]LogStats: UGameplayTagsManager::InitializeManager -  0.001 s
[2021.10.30-16.10.18:225][  0]LogInit: Initializing FReadOnlyCVARCache
[2021.10.30-16.10.18:225][  0]LogNetVersion: Set ProjectVersion to 0.0.1.0. Version Checksum will be recalculated on next use.
[2021.10.30-16.10.18:225][  0]LogInit: Texture streaming: Disabled
[2021.10.30-16.10.18:242][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.10.30-16.10.18:242][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.10.30-16.10.18:242][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2021.10.30-16.10.18:242][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.10.30-16.10.18:242][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.10.30-16.10.18:242][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2021.10.30-16.10.18:242][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.10.30-16.10.18:242][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.10.30-16.10.18:242][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
CommonUnixCrashHandler: Signal=11
[2021.10.30-16.10.18:265][  0]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000070
LogOnline: OSS: Creating online subsystem instance for: EOS
[2021.10.30-16.10.18:265][  0]LogCore: Fatal error!
LogSteamShared: Display: Loading Steam SDK 1.47
0x00007f09d55388cf libUE4Server-FactoryGame-Linux-Shipping.so!UFGServerSubsystem::Initialize(FSubsystemCollectionBase&) [D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/Server/FGServerSubsystem.cpp:170]
0x00007f0a031e840a libUE4Server-Engine-Linux-Shipping.so!FSubsystemCollectionBase::AddAndInitializeSubsystem(UClass*) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Engine/Private/Subsystems/SubsystemCollection.cpp:209]
0x00007f0a031e7a3e libUE4Server-Engine-Linux-Shipping.so!FSubsystemCollectionBase::Initialize(UObject*) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Engine/Private/Subsystems/SubsystemCollection.cpp:132]
0x00007f0a02c1e56f libUE4Server-Engine-Linux-Shipping.so!UGameInstance::Init() [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Engine/Private/GameInstance.cpp:99]          SS: Unable to create OnlineSubsystem module STEAM
0x00007f09d5302c51 libUE4Server-FactoryGame-Linux-Shipping.so!UFGGameInstance::Init() [D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/FGGameInstance.SS: Creating online subsystem instance for: STEAM
cpp:78]
0x00007f0a02bf8fe3 libUE4Server-Engine-Linux-Shipping.so!UGameEngine::Init(IEngineLoop*) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Engine/Private/GameEngi
ne.cpp:1107]
0x00007f09d53026ba libUE4Server-FactoryGame-Linux-Shipping.so!UFGGameEngine::Init(IEngineLoop*) [D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/FGGameEngine.cpp:40]
0x0000000000214c4e UE4Server-Linux-Shipping!FEngineLoop::Init() [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:4008]
0x000000000021623c UE4Server-Linux-Shipping!GuardedMain(char16_t const*) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Launch/Private/Launch.cpp:153]
0x00007f0a00cd1dc5 libUE4Server-UnixCommonStartup-Linux-Shipping.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
0x00007f0a00b2509b libc.so.6!__libc_start_main(+0xea)
0x0000000000214709 UE4Server-Linux-Shipping!_start()

[2021.10.30-16.10.18:281][  0]LogExit: Executing StaticShutdownAfterError
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
/home/steam/run.sh: line 53:   107 Segmentation fault      Engine/Binaries/Linux/UE4Server-Linux-Shipping FactoryGame -log -NoSteamClient -unattended
```

**Comment by wolveix** [comment]
This looks like a bug with the game, not the server. Check that you have enough resources available to host (5GB+ RAM, reasonably modern CPU)

**Comment by indietyp** [comment]
My current memory looks like this:
```
              total        used        free      shared  buff/cache   available
Mem:           62Gi       5.4Gi        38Gi        85Mi        18Gi        57Gi
Swap:          31Gi        52Mi        31Gi
```

I am also running on an `AMD Ryzen 5 3600 6-Core Processor`, so I think it might be unlikely that it is a resource issue.

**Comment by wolveix** [comment]
Could you try running the `dev` tag, please?

**Comment by indietyp** [comment]
The `dev` tag had the same problem. removing the existing config directory resulted in #60

**Comment by wolveix** [comment]
I'm able to reproduce. Working on a fix now.

**Comment by wolveix** [comment]
This is now fixed. I had to rollback the change that addresses #57, so I need to rethink that part.

**Comment by indietyp** [comment]
maybe reopen #57 and close this issue?

**Comment by indietyp** [comment]
thanks for all the quick work!

**Comment by wolveix** [comment]
This issue is already closed.

**Comment by mythmon** [comment]
I'm still getting segfaults with the `latest` tag, with image ID `c59fd23e9ddc`. My log looks a lot like @indietyp's, including the "Steam API failed to initialize right before a segfault reading address 0x70.

**Comment by wolveix** [comment]
Could you try the following:
- Delete your mapped config directory (backup if needed)
- Pull the latest image just in case

Then try running. If it doesn't work, please paste your full Docker command as well as your log :) Ideally in a new issue please!

**Comment by mythmon** [comment]
Ok, that seems to have fixed it. I think my volume mounts to backup my save files collided with the recent symlinks you added. I cleared that all away and it seems to work now. Thanks again.
